import { getLocale } from "eez-studio-shared/i10n";

const translations: Record<string, Record<string, string>> = {
    en: {},
    "zh-CN": {
        Save: "保存",
        Copy: "复制",
        Paste: "粘贴",
        Cut: "剪切",
        Scrapbook: "剪贴簿",
        Configuration: "配置",
        Check: "检查",
        Build: "构建",
        "Run MicroPython Script": "运行 MicroPython 脚本",
        "Show front face": "显示正面",
        "Show back face": "显示背面",
        "Show timeline": "显示时间轴",
        "Show component descriptions": "显示组件说明",
        Edit: "编辑",
        "Enter edit mode (Shift+F5)": "进入编辑模式（Shift+F5）",
        Run: "运行",
        "Enter run mode (F5)": "进入运行模式（F5）",
        Debug: "调试",
        "Enter debug mode (Ctrl+F5)": "进入调试模式（Ctrl+F5）",
        COMPACT_DATABASE_MESSAGE: "建议每 30 天压缩一次数据库。",
        MAKE_ACTIVE_DB: "是否将该数据库设为活动数据库？",
        RESTART_APP: "是否重启应用？",
        RESTART_REQUIRED: "需要重启以完成新数据库的激活。",

        Open: "打开",
        Create: "新建",
        Examples: "示例",
        Instruments: "仪器",
        Extensions: "扩展",
        Settings: "设置",
        "Open a local project or select one from the recent list": "打开本地项目或从最近列表中选择",
        "Create a new project": "新建项目",
        "Example projects ready to run or edit": "示例项目，可直接运行或编辑",
        "Instruments manager": "仪器管理",
        "Extensions manager": "扩展管理",
        "Global user settings": "全局用户设置"
        ,
        "Sort alphabetically": "按字母排序",
        "Show most recent first": "按最近优先显示",
        "Open Project": "打开项目",
        "Open a local EEZ Studio Project": "打开本地 EEZ Studio 项目",
        "Edit Project": "编辑项目",
        "Run Project": "运行项目",
        "Copy Project Path": "复制项目路径",
        "Remove From List": "从列表中移除",

        "Install Extension": "安装扩展",
        "Install extension for this instrument": "为该仪器安装扩展",
        "Open in Tab": "在标签页中打开",
        "Open instrument in new tab": "在新标签页打开仪器",
        "Open in New Window": "在新窗口中打开",
        "Open instrument in new window": "在新窗口打开仪器",
        "Delete": "删除",
        "Delete instrument": "删除仪器",
        "Add Instrument": "添加仪器",
        "Add instrument": "添加仪器",
        "Deleted Instruments": "已删除的仪器",
        "Show deleted instruments": "显示已删除的仪器",
        "Export": "导出",
        "Export to database": "导出到数据库",
        "Import": "导入",
        "Import from database": "从数据库导入",
        "Properties": "属性",
        "Connection": "连接",
        "Interface": "接口",
        "Ethernet": "以太网",
        "Server address": "服务器地址",
        "Port": "端口",
        "Serial": "串口",
        "Baud rate": "波特率",
        "Data bits": "数据位",
        "Stop bits": "停止位",
        "Parity": "校验位",
        "Flow control": "流控",
        "USBTMC": "USBTMC",
        "Vendor ID": "厂商ID",
        "Product ID": "产品ID",
        "WebSimulator": "Web仿真器",
        "VISA": "VISA",
        "Resource": "资源",
        "Installing...": "正在安装...",
        "Extensions successfully installed!": "扩展安装成功！",
        "Instrument extension not found!": "未找到仪器扩展！",
        "Instrument": "仪器",
        "ID": "ID",
        "Label": "标签",
        "IDN": "IDN",
        "Auto connect": "自动连接",
        "Connect": "连接",
        "Disconnect": "断开",
        "Abort": "中止",
        "Creation date: ": "创建日期：",
        "unknown": "未知",
        "Restore": "恢复",
        "Delete Permanently": "永久删除",
        "Delete instrument permanently including all the history": "永久删除该仪器并清除全部历史",
        "Are you sure?": "确定执行该操作？",
        "It will also delete all the history.": "这也会删除所有历史记录。",
        "Delete All Permanently": "全部永久删除",

        "dashboard": "仪表盘",
        "Untitled project": "未命名项目",
        "Components Documentation Browser": "组件文档浏览器",
        "Master": "主视图",
        "Details": "详情",
        "TOC": "目录",
        "Content": "内容",
        "Show": "显示",
        "Tab": "标签页",
        "Disable all breakpoints": "禁用所有断点",
        "Enable all breakpoints": "启用所有断点",
        "Remove selected breakpoint": "移除选中的断点",
        "Remove all breakpoints": "移除所有断点",
        "Disable breakpoint": "禁用断点",
        "Enable breakpoint": "启用断点",
        "Memory usage": "内存使用",
        "Resume (F5)": "继续 (F5)",
        "Pause (F6)": "暂停 (F6)",
        "Step over (F10)": "单步越过 (F10)",
        "Step into (F11)": "单步进入 (F11)",
        "Step out (Shift + F11)": "单步跳出 (Shift + F11)",
        "Toggle Replace": "切换替换",
        "Search": "搜索",
        "Match Case": "区分大小写",
        "Match Whole Word": "匹配整个单词",
        "Refresh Search Results": "刷新搜索结果",
        "Next Result": "下一个结果",
        "Previous Result": "上一个结果",
        "Replace": "替换",
        "Replace Selected": "替换所选",
        "Replace All": "全部替换",
        "Name": "名称",
        "Value": "值",
        "Type": "类型",
        "Add Watch Expression": "添加监视表达式",
        "Edit Watch Expression": "编辑监视表达式",
        "Delete Watch Expression": "删除监视表达式",
        "Show finished flows": "显示已完成的流程",
        "All": "全部",
        "Filter:": "过滤：",
        "Clear logs": "清空日志",
        "Nothing selected": "未选择对象",
        "Multiple objects selected": "已选择多个对象",
        "This feature can't be removed": "此功能不可移除",
        "Remove feature from the project": "从项目中移除此功能",
        "Add feature to the project": "向项目添加此功能",
        "Delete Selected Item": "删除选中的项",
        "Remove": "移除",
        "Add": "添加",
        "Are you sure you want to remove this feature?": "确定要移除此功能吗？",
        "Fatal": "致命",
        "Error": "错误",
        "Warning": "警告",
        "Info": "信息",
        "SCPI": "SCPI",
        "Copy to Clipboard": "复制到剪贴板",
        "TIP": "提示",
        "From your code you neeed to set a destination group for a particular input device using lv_indev_set_group. Below is an example code that does that.": "在代码中需要为特定输入设备设置目标分组，使用 lv_indev_set_group。下面是一个示例代码。",
        "No changes": "无更改",
        "No changes!": "无更改！",
        "Export to XLIFF": "导出为 XLIFF",
        "XLIFF files": "XLIFF 文件",
        "All Files": "所有文件",
        "XLIFF file format version": "XLIFF 文件格式版本",
        "File saved!": "文件已保存！",
        "Import from XLIFF": "从 XLIFF 导入",
        "Import into language": "导入到语言",
        "Updated": "已更新",
        "translation(s)": "条翻译",
        "in language": "于语言",
        "Progress": "进度",
        "Available languages": "可用语言",
        "Available text resources": "可用文本资源",
        "Total strings": "字符串总数",
        "No. translations": "翻译条目数",

        "Cancel": "取消",
        "OK": "确定",
        "Detected Instrument Command Changes": "检测到仪器命令变更",
        "Detected SCPI Command Changes": "检测到 SCPI 命令变更"
        ,
        "Refresh with content from commands help folder": "用命令帮助文件夹内容刷新",
        "Refresh with content from SCPI help folder": "用 SCPI 帮助文件夹内容刷新",
        "No help page defined!": "未定义帮助页面！",
        "SCPI help folder is not defined": "未定义 SCPI 帮助文件夹",
        "Commands help folder is not defined": "未定义命令帮助文件夹",
        "SCPI help folder": "SCPI 帮助文件夹",
        "Commands help folder": "命令帮助文件夹",
        "doesn't exists.": "不存在。",
        "File doesn't exists": "文件不存在",
        "(build disabled)": "（禁止构建）",
        "ADDED": "新增",
        "REMOVED": "已移除",
        "UPDATED": "已更新",
        "Pages": "页面",
        "User Widgets": "用户组件",
        "User Actions": "用户动作",
        "Widgets Structure": "组件结构",
        "Variables": "变量",
        "Components Palette": "组件面板",
        "Breakpoints": "断点",
        "Styles": "样式",
        "Fonts": "字体",
        "Bitmaps": "位图",
        "Themes": "主题",
        "Texts": "文本",
        "Instrument Commands": "仪器命令",
        "IEXT": "IEXT",
        "Changes": "更改",
        "Checks": "检查",
        "Output": "输出",
        "References": "引用",
        "Active Flows": "活动流程",
        "Watch": "监视",
        "Queue": "队列",
        "Logs": "日志",
        "Preview": "预览",
        "Text resources": "文本资源",
        "Languages": "语言",
        "Statistics": "统计",
        "Groups": "分组",
        "Group Widgets": "分组组件",
        "Keep Tab Open": "固定标签页",
        "Updating...": "正在更新...",
        "Install missing extensions": "安装缺失的扩展",
        "Install missing extension": "安装缺失的扩展",
        "Install": "安装",
        "Unknown extension": "未知扩展",
        "Install All": "全部安装",
        "Undo": "撤销",
        "Redo": "重做",
        "Add Action": "添加动作",
        "Add Widget": "添加组件",
        "Add Action...": "添加动作...",
        "Add Widget...": "添加组件...",
        "Zoom to": "缩放到",
        "Global zoom": "全局缩放",
        "EEZ Project": "EEZ 项目"
        ,
        "IP Address": "IP 地址",
        "This property is optional": "该属性为可选",
        "Max. Connections": "最大连接数",
        "invalid IP Address property": "无效的 IP 地址属性",
        "invalid Port property": "无效的端口属性",
        "invalid Max. connections property": "无效的最大连接数属性",
        "Never started": "从未启动",
        "Ready": "就绪",
        "Data": "数据",
        "Close": "关闭",
        "End": "结束",
        "Timeout": "超时",
        "Event": "事件",

        "Action": "动作",
        "All event handlers are already defined": "所有事件处理器均已定义",
        "New Event Handler": "新建事件处理器",
        "tcp socket is not connected": "TCP 套接字未连接",
        "tcp socket not found": "未找到 TCP 套接字",
        "invalid Data property": "无效的数据属性",
        "TCP socket not found": "未找到 TCP 套接字",
        "Advanced options are set via JSON value, check": "高级选项通过 JSON 值设置，请查看",
        "Tabulator documentation": "Tabulator 文档",
        "for available options.": "以了解可用选项。",
        "The options are copied as a JSON literal to the clipboard": "选项已作为 JSON 字面量复制到剪贴板",
        "Copy options as a JSON literal to the clipboard": "复制选项为 JSON 字面量到剪贴板",
        "Copy Options": "复制选项",
        "Sync columns with structure": "与结构同步列",
        "Structure": "结构",
        "Select Structure": "选择结构",
        "Build From Structure Definition": "根据结构定义生成",
        "Invalid JSON": "JSON 无效",
        '"Selectable rows" should be either empty, true, false, number or highlight': '“可选行”应为空、true、false、数字或 highlight',
        "Field": "字段",
        "not found in the structure": "在该结构中未找到",
        "Basic options": "基础选项",
        "Advanced options": "高级选项",
        "Persistent configuration": "持久化配置"
        ,
        "Inline script": "内联脚本",
        "Inline script as expression": "作为表达式的内联脚本",
        "Script file": "脚本文件",
        "Invalid script source": "无效的脚本来源",
        "Handle not defined": "未定义句柄",
        "Invalid handle": "无效的句柄",
        "Message not defined": "未定义消息",
        "File": "文件",
        "View": "视图",
        "Window": "窗口",
        "Help": "帮助",
        "About": "关于",
        "Documentation": "文档",
        "Minimize": "最小化",
        "Bring All to Front": "全部置于前端",
        "Select All": "全选",
        "New Project...": "新建项目...",
        "Add Instrument...": "添加仪器...",
        "New Window": "新建窗口",
        "Open...": "打开...",
        "Open Recent": "打开最近",
        "Reload Project": "重新加载项目",
        "Load Debug Info...": "加载调试信息...",
        "EEZ Debug Info": "EEZ 调试信息",
        "Save Debug Info...": "保存调试信息...",
        "Import Instrument Definition...": "导入仪器定义...",
        "Instrument Definition Files": "仪器定义文件",
        "Save As": "另存为",
        "Build Extensions": "构建扩展",
        "Build and Install Extensions": "构建并安装扩展",
        "Close Window": "关闭窗口",
        "Exit": "退出",
        "Find Project Component": "查找项目组件",
        "Home": "主页",
        "History": "历史",
        "Shortcuts and Groups": "快捷方式与分组",
        "Noteboooks": "笔记本",
        "Scrapbook for Project Editor": "项目编辑器剪贴簿",
        "Toggle Full Screen": "切换全屏",
        "Toggle Developer Tools": "切换开发者工具",
        "Switch to Light Theme": "切换到浅色主题",
        "Switch to Dark Theme": "切换到深色主题",
        "Zoom In": "放大",
        "Zoom Out": "缩小",
        "Reset Zoom": "重置缩放",
        "Hide Components Palette": "隐藏组件面板",
        "Show Components Palette": "显示组件面板",
        "Reset Layout": "重置布局",
        "Next Tab": "下一个标签页",
        "Previous Tab": "上一个标签页",
        "Reload": "重新加载",
        "Services": "服务",
        "Hide": "隐藏",
        "Hide Others": "隐藏其他",
        "Show All": "显示全部",
        "Quit": "退出",
        "File does not exist.": "文件不存在。",
        "The file": "文件",
        "does not seem to exist anymore.": "似乎已不存在。",

        "General": "通用",
        "Project features": "项目功能",
        "Undefined": "未定义",
        "EEZ-GUI": "EEZ-GUI",
        "EEZ-GUI Library": "EEZ-GUI 库",
        "BB3 MicroPython Script": "BB3 MicroPython 脚本",
        "BB3 Applet": "BB3 小程序",
        "Dashboard": "仪表盘",
        "LVGL": "LVGL",
        "Project type": "项目类型",
        "Target BB3 firmware": "目标 BB3 固件",
        "Project version": "项目版本",
        "LVGL version": "LVGL 版本",
        "SCPI documentation folder": "SCPI 文档文件夹",
        "Commands documentation folder": "命令文档文件夹",
        "After adding an extension, you need to reload the project to see the changes. To reload the project select 'Reload Project' from the 'File' menu.": "添加扩展后，需要重新加载项目才能看到更改。要重新加载项目，请在“文件”菜单中选择“重新加载项目”。",
        "Imports": "导入",
        "Display width": "显示宽度",
        "Display height": "显示高度",
        "Circular display": "圆形显示",
        "Display border radius": "显示边框圆角",
        "Dark theme": "深色主题",
        "Color format": "颜色格式",
        "Flow support": "流程支持",
        "Hidden widget lines": "隐藏控件线条",
        "Fully visible": "完全可见",
        "Dimmed": "变暗",
        "Hidden": "隐藏",
        "Dimmed lines opacity (%)": "变暗线条不透明度（%）",
        "Title": "标题",
        "Icon": "图标",
        "Description": "描述",
        "Image": "图片",
        "Keywords": "关键字",
        "Target platform": "目标平台",
        "Target instrument": "目标仪器",
        "Target platform link": "目标平台链接",
        "Target instrument link": "目标仪器链接",
        "Author": "作者",
        "Author link": "作者链接",
        "Min. studio version": "最低 Studio 版本",
        "Resource files": "资源文件",
        "Item": "项目",
        "User Widget": "用户组件",
        "User Action": "用户动作",
        "Style": "样式",
        "Group": "分组",
        "Global": "全局",
        "Local": "本地",
        "Structs": "结构体",
        "Enums": "枚举",
        "Widgets": "组件",
        "Actions": "动作",
        "Basic": "基础",
        "Other components": "其他组件",
        "Input": "输入",
        "Visualiser": "可视化",
        "Indentation": "缩进",
        "Specific": "特定",
        "Layout": "布局",
        "Flow": "流程",
        "Position and size": "位置与尺寸",
        "Timeline keyframe": "时间轴关键帧",
        "Duplicate": "复制副本",
        "Find All References": "查找所有引用",
        "Reset All Modifications": "重置所有修改",
        "Create New Style": "创建新样式",
        "New Style": "新样式",
        "Bar": "进度条",
        "Tab bar": "标签栏",
        "List": "列表",
        "TOP": "上",
        "LEFT": "左",
        "BOTTOM": "下",
        "RIGHT": "右"
        ,
        "Update Style": "更新样式",
        "Copy to other themes": "复制到其他主题",
        "New Color": "新颜色",
        "Color name": "颜色名称",
        "Put in Select": "放入选择框",
        "Put in Container": "放入容器",
        "Put in List": "放入列表",
        "Create User Widget": "创建用户组件",
        "Replace with User Widget": "替换为用户组件",
        "Resize...": "调整大小...",
        "Resize Widget": "调整控件大小",
        "Copy position and size": "复制位置与尺寸",
        "Paste position and size": "粘贴位置与尺寸",
        "Widget is outside of its parent": "控件超出父容器范围",
        "Remove Breakpoint": "移除断点",
        "Disable Breakpoint": "禁用断点",
        "Enable Breakpoint": "启用断点",
        "Add Breakpoint": "添加断点",
        "OFF": "关闭",
        "ON": "开启",
        "ACTIVE": "激活",
        "AUTO": "自动",
        "NONE": "无",
        "HOR": "水平",
        "VER": "垂直",
        "ALL": "全部",
        "START": "开始",
        "END": "结束",
        "CENTER": "居中",
        "Scroll direction": "滚动方向",
        "Scroll snap X": "滚动捕捉 X",
        "Scroll snap Y": "滚动捕捉 Y",
        "Checked": "选中",
        "Disabled": "禁用",
        "FreeType": "FreeType",
        "OpenType": "OpenType",
        "Floating": "浮动",
        "Fixed": "固定",
        "Variable": "变量",
        "Assignable": "可赋值",
        "1.7.X or older": "1.7.X 或更早",
        "1.8 or newer": "1.8 或更新",
        "Proprietary": "专有协议"
        ,
        "Binary output format": "二进制输出格式",
        "RGB332": "RGB332",
        "RGB565": "RGB565",
        "RGB565 Swap": "RGB565 交换",
        "RGB888": "RGB888"
        ,
        "Deselect": "取消选择",
        "Select for Compare": "选择进行对比",
        "Refresh": "刷新",
        "Compare with other project": "与其他项目比较"
        ,
        "Add Characters": "添加字符",
        "Font files": "字体文件",
        "Font size (points)": "字体大小（点）",
        "File not found": "文件未找到",
        "Add single character at the end": "在末尾添加单个字符",
        "Add characters from range": "从范围添加字符",
        "Add missing characters": "添加缺失字符",
        "Select one or more type": "选择一个或多个类型",
        "Integer (NR1)": "整数 (NR1)",
        "Decimal (NR2)": "十进制 (NR2)",
        "Real (NR3)": "实数 (NR3)"
        ,
        "Center View": "视图居中",
        "Center View on All Pages": "在所有页面居中",
        "Set the Same Zoom for All Pages": "为所有页面设置相同缩放"
        ,
        "POSITION AND SIZE": "位置与尺寸",
        "LAYOUT": "布局",
        "PADDING": "内边距",
        "MARGIN": "外边距",
        "BACKGROUND": "背景",
        "BORDER": "边框",
        "OUTLINE": "轮廓",
        "SHADOW": "阴影",
        "IMAGE": "图像",
        "LINE": "线条",
        "ARC": "圆弧",
        "TEXT": "文本",
        "MISCELLANEOUS": "杂项",
        "DEFAULT": "默认",
        "CHECKED": "选中",
        "PRESSED": "按下",
        "CHECKED|PRESSED": "选中|按下",
        "DISABLED": "禁用",
        "FOCUSED": "聚焦",
        "FOCUS_KEY": "按键聚焦",
        "EDITED": "编辑中",
        "SCROLLED": "滚动中",
        "UNCHECKED": "未选中",
        "PRESSING": "按压中",
        "PRESS_LOST": "按压丢失",
        "SHORT_CLICKED": "短点击",
        "LONG_PRESSED": "长按",
        "LONG_PRESSED_REPEAT": "长按重复",
        "CLICKED": "点击",
        "RELEASED": "释放",
        "SCROLL_BEGIN": "滚动开始",
        "SCROLL_THROW_BEGIN": "惯性滚动开始",
        "SCROLL_END": "滚动结束",
        "SCROLL": "滚动",
        "GESTURE": "手势",
        "KEY": "按键",
        "ROTARY": "旋钮",
        "DEFOCUSED": "失焦",
        "LEAVE": "离开",
        "HIT_TEST": "命中测试",
        "INDEV_RESET": "输入设备重置",
        "HOVER_OVER": "悬停进入",
        "HOVER_LEAVE": "悬停离开",
        "COVER_CHECK": "覆盖检查",
        "REFR_EXT_DRAW_SIZE": "刷新额外绘制大小",
        "DRAW_MAIN_BEGIN": "主绘制开始",
        "DRAW_MAIN": "主绘制",
        "DRAW_MAIN_END": "主绘制结束",
        "DRAW_POST_BEGIN": "后绘制开始",
        "DRAW_POST": "后绘制",
        "DRAW_POST_END": "后绘制结束",
        "DRAW_PART_BEGIN": "部分绘制开始",
        "DRAW_PART_END": "部分绘制结束",
        "DRAW_TASK_ADDED": "绘制任务添加",
        "VALUE_CHANGED": "值改变",
        "INSERT": "插入",
        "REFRESH": "刷新",
        "READY": "就绪",
        "CANCEL": "取消",
        "CREATE": "创建",
        "DELETE": "删除",
        "CHILD_CHANGED": "子项变化",
        "CHILD_CREATED": "子项创建",
        "CHILD_DELETED": "子项删除",
        "SCREEN_UNLOAD_START": "屏幕卸载开始",
        "SCREEN_LOAD_START": "屏幕加载开始",
        "SCREEN_LOADED": "屏幕已加载",
        "SCREEN_UNLOADED": "屏幕已卸载",
        "SIZE_CHANGED": "尺寸改变",
        "STYLE_CHANGED": "样式改变",
        "LAYOUT_CHANGED": "布局改变",
        "GET_SELF_SIZE": "获取自身尺寸",
        "INVALIDATE_AREA": "区域失效",
        "RESOLUTION_CHANGED": "分辨率改变",
        "COLOR_FORMAT_CHANGED": "颜色格式改变",
        "REFR_REQUEST": "刷新请求",
        "REFR_START": "刷新开始",
        "REFR_READY": "刷新就绪",
        "RENDER_START": "渲染开始",
        "RENDER_READY": "渲染就绪",
        "FLUSH_START": "刷新输出开始",
        "FLUSH_FINISH": "刷新输出结束",
        "FLUSH_WAIT_START": "刷新等待开始",
        "FLUSH_WAIT_FINISH": "刷新等待结束",
        "VSYNC": "垂直同步",
        "part": "部分",
        "Main": "主",
        "Scrollbar": "滚动条",
        "Indicator": "指示器",
        "Knob": "旋钮",
        "Selected": "已选",
        "Items": "项",
        "Ticks": "刻度",
        "Cursor": "光标",

        "Integer": "整数",
        "Fraction": "小数",
        "Fraction and unit": "小数与单位",
        "Unit": "单位",
        "Integer and fraction": "整数与小数",
        "Align": "对齐",
        "Flex flow": "弹性布局方向",
        "Flex main place": "主轴分布",
        "Flex cross place": "交叉轴分布",
        "Flex track place": "轨道分布",
        "Flex grow": "弹性增长",
        "Grid column align": "网格列对齐",
        "Grid row align": "网格行对齐",
        "Grid row descriptor": "网格行描述",
        "Grid column descriptor": "网格列描述",
        "Grid cell column pos": "单元格列位置",
        "Grid cell column span": "单元格列跨越",
        "Grid cell row pos": "单元格行位置",
        "Grid cell row span": "单元格行跨越",
        "Grid cell X align": "单元格 X 对齐",
        "Grid cell Y align": "单元格 Y 对齐",
        "Grad. direction": "渐变方向",
        "Dither mode": "抖动模式",
        "Grad. color": "渐变颜色",
        "Main stop": "主渐变起点",
        "Gradient stop": "渐变终点",
        "Image source": "图像源",
        "Image opacity": "图像不透明度",
        "Image recolor": "图像重着色",
        "Image recolor opa.": "图像重着色不透明度",
        "Image tiled": "平铺图像",
        "Side": "侧边",
        "Post": "后绘制",
        "Color": "颜色",
        "Opacity": "不透明度",

        "X offset": "X 偏移",
        "Y offset": "Y 偏移",
        "Spread": "扩散半径",
        "Rounded": "圆角",
        "Dash width": "虚线宽度",
        "Dash gap": "虚线间隔",
        "Recolor": "重着色",
        "Recolor opacity": "重着色不透明度",
        "Font": "字体",
        "Letter space": "字间距",
        "Line space": "行间距",
        "Radius": "圆角半径",
        "Clip corner": "裁剪角",
        "Decoration": "修饰",
        "Blend mode": "混合模式",
        "Base direction": "基准方向",
        "Translate X": "平移 X",
        "Translate Y": "平移 Y",
        "Transform scale X": "缩放 X",
        "Transform scale Y": "缩放 Y",
        "Transform zoom": "缩放",
        "Transform angle": "旋转角度",
        "Transform rotation": "旋转",
        "Transform pivot X": "旋转中心 X",
        "Transform pivot Y": "旋转中心 Y",
        "Transform skew X": "倾斜 X",
        "Transform skew Y": "倾斜 Y",
        "Length": "长度",
        "Min. width": "最小宽度",
        "Max. width": "最大宽度",
        "Min. height": "最小高度",
        "Max. height": "最大高度",
        "Width": "宽度",
        "Height": "高度",
        "Row": "行",
        "Column": "列",
        "Top": "上",
        "Bottom": "下",
        "Left": "左",
        "Right": "右",
        "TOP_LEFT": "左上",
        "TOP_MID": "上中",
        "TOP_RIGHT": "右上",
        "BOTTOM_LEFT": "左下",
        "BOTTOM_MID": "下中",
        "BOTTOM_RIGHT": "右下",
        "LEFT_MID": "左中",
        "RIGHT_MID": "右中",
        "OUT_TOP_LEFT": "外部左上",
        "OUT_TOP_MID": "外部上中",
        "OUT_TOP_RIGHT": "外部右上",
        "OUT_BOTTOM_LEFT": "外部左下",
        "OUT_BOTTOM_MID": "外部下中",
        "OUT_BOTTOM_RIGHT": "外部右下",
        "OUT_LEFT_TOP": "外部左上",
        "OUT_LEFT_MID": "外部左中",
        "OUT_LEFT_BOTTOM": "外部左下",
        "OUT_RIGHT_TOP": "外部右上",
        "OUT_RIGHT_MID": "外部右中",
        "OUT_RIGHT_BOTTOM": "外部右下",
        "STRETCH": "拉伸",
        "SPACE_EVENLY": "平均间隔",
        "SPACE_AROUND": "环绕间隔",
        "SPACE_BETWEEN": "两端间隔",
        "ROW": "行",
        "COLUMN": "列",
        "ROW_WRAP": "行换行",
        "ROW_REVERSE": "行反向",
        "ROW_WRAP_REVERSE": "行换行反向",
        "COLUMN_WRAP": "列换行",
        "COLUMN_REVERSE": "列反向",
        "COLUMN_WRAP_REVERSE": "列换行反向",
        "ORDERED": "有序",
        "ERR_DIFF": "误差扩散",
        "UNDERLINE": "下划线",
        "STRIKETHROUGH": "删除线",
        "NORMAL": "正常",
        "ADDITIVE": "相加",
        "SUBTRACTIVE": "相减",
        "MULTIPLY": "相乘",
        "REPLACE": "替换",
        "LTR": "从左到右",
        "RTL": "从右到左",
        "FULL": "全边框",
        "INTERNAL": "内部",
        "Bg main opa": "主色不透明度",
        "Bg grad opa": "渐变不透明度",
        "Bg grad": "渐变定义",
        "Transition": "过渡",
        "Flags": "标志",
        "States": "状态",
        "FLEX": "弹性布局",
        "GRID": "网格布局",
        "Padding": "内边距",
        "Clickable": "可点击",
        "Scrollbar mode": "滚动条模式",
        "Absolute pos.": "绝对位置",
        "No. of images": "图像数量",
        "Repeat count": "重复次数",
        "Indicator type": "指示器类型",
        "Major tick distance": "主刻度间距",
        "Major tick line width": "主刻度线宽",
        "Major tick label": "主刻度标签",
        "Major Tick label gap": "主刻度标签间距",
        "Position": "位置",
        "Size": "尺寸",
        "User widget": "用户组件",
        "Year": "年",
        "Month": "月",
        "Day": "日",
        "Change pivot point (default is center)": "改变旋转中心（默认居中）",
        "Pivot X": "旋转中心 X",
        "Pivot Y": "旋转中心 Y",
        "Scale": "缩放",
        "Rotation": "旋转",
        "Released image": "释放态图像",
        "Pressed image": "按下态图像",
        "Disabled image": "禁用态图像",
        "Checked released image": "选中释放态图像",
        "Checked pressed image": "选中按下态图像",
        "Checked disabled image": "选中禁用态图像",
        "Invert Y": "反转 Y",
        "Use this for Encoder in simulator": "用于模拟器中的编码器",
        "Use this for Keyboard in simulator": "用于模拟器中的键盘",
        "LVGL Groups": "LVGL 分组",
        "Action type": "动作类型",
        "Previous screen": "前一个屏幕",
        "Speed (ms)": "速度 (毫秒)",
        "Delay (ms)": "延迟 (毫秒)",
        "Time (ms)": "时间 (毫秒)",
        "Target": "目标",
        "HIDDEN": "隐藏",

        "CHECKABLE": "可选中",
        "NO_REPEAT": "不重复",
        "CLICK_TRIG": "点击触发",
        "POPOVER": "气泡",
        "RECOLOR": "重着色",
        "CUSTOM_1": "自定义 1",
        "CUSTOM_2": "自定义 2"
        ,


        "QR code update": "二维码更新",

        "Text": "文本",
        "Start": "开始",
        "Evaluate": "求值",
        "SetVariable": "设置变量",
        "SwitchCase": "条件分支",
        "Compare": "比较",
        "IsTrue": "为真判断",
        "TestAndSet": "测试并置位",
        "Delay": "延时",
        "Loop": "循环",
        "Counter": "计数器",
        "Constant": "常量",
        "Log": "日志",
        "CatchError": "捕获错误",
        "Label IN": "标签输入",
        "Label OUT": "标签输出",
        "NoOp": "空操作",
        "Comment": "注释",
        "Animate": "动画",
        "SetColorTheme": "设置颜色主题",
        "GUI": "界面",
        "MQTTInit": "MQTT 初始化",
        "MQTTEvent": "MQTT 事件",
        "MQTTConnect": "MQTT 连接",
        "MQTTDisconnect": "MQTT 断开",
        "MQTTSubscribe": "MQTT 订阅",
        "MQTTUnsubscribe": "MQTT 取消订阅",
        "MQTTPublish": "MQTT 发布",
        "Long mode": "长文本模式",
        "WRAP": "自动换行",
        "DOT": "省略号",
        "SCROLL_CIRCULAR": "循环滚动",
        "CLIP": "裁剪",

        "Click focusable": "可点击聚焦",
        "Checkable": "可选中",
        "Scrollable": "可滚动",
        "Scroll elastic": "滚动弹性",
        "Scroll momentum": "滚动惯性",
        "Scroll one": "单项滚动",
        "Scroll chain hor": "水平链式滚动",
        "Scroll chain ver": "垂直链式滚动",
        "Scroll on focus": "聚焦时滚动",
        "Scroll with arrow": "方向键滚动",
        "Snappable": "可捕捉",
        "Press lock": "按压锁定",
        "Event bubble": "事件冒泡",
        "Gesture bubble": "手势冒泡",
        "Adv hittest": "高级命中测试",
        "Ignore layout": "忽略布局",
        "Overflow visible": "溢出可见",
        "Code identifier": "代码标识符",
        "This identifier will be used in the generated source code in the \"Objects\" struct. It is different from the \"Name\" above because in the source code we are following \"lowercase with underscore\" naming convention.": "此标识符将用于生成的源代码中的 \"Objects\" 结构体。它与上面的 \"Name\" 不同，因为源代码遵循 \"下划线小写\" 的命名约定。",
        "Options": "选项",
        "Mode": "模式",
        "INFINITE": "循环",
        "SYMMETRICAL": "对称",
        "RANGE": "范围"
        ,
        "Literal": "字面量",
        "Translated literal": "可翻译字面量",
        "Expression": "表达式",
        "CLICKABLE": "可点击",
        "CLICK_FOCUSABLE": "可点击聚焦",
        "SCROLLABLE": "可滚动",
        "SCROLL_ELASTIC": "滚动弹性",
        "SCROLL_MOMENTUM": "滚动惯性",
        "SCROLL_ONE": "单项滚动",
        "SCROLL_CHAIN_HOR": "水平链式滚动",
        "SCROLL_CHAIN_VER": "垂直链式滚动",
        "SCROLL_ON_FOCUS": "聚焦时滚动",
        "SCROLL_WITH_ARROW": "方向键滚动",
        "SNAPPABLE": "可捕捉",
        "PRESS_LOCK": "按压锁定",
        "EVENT_BUBBLE": "事件冒泡",
        "GESTURE_BUBBLE": "手势冒泡",
        "AnimationImage": "动画图像",
        "Arc": "圆弧",
        "Button": "按钮",
        "ButtonMatrix": "按钮矩阵",
        "Calendar": "日历",
        "Canvas": "画布",
        "Chart": "图表",
        "Checkbox": "复选框",
        "Colorwheel": "色轮",
        "Container": "容器",
        "Dropdown": "下拉列表",
        "Imgbutton": "图片按钮",
        "Keyboard": "键盘",
        "Led": "LED 指示灯",
        "Line": "线条",
        "Lottie": "Lottie 动画",
        "Menu": "菜单",
        "MessageBox": "消息框",
        "Meter": "仪表",
        "Panel": "面板",
        "QRCode": "二维码",
        "Roller": "滚轮",
        "ScaleWidget": "刻度尺",
        "Screen": "屏幕",
        "Slider": "滑块",
        "Span": "文本跨度",
        "Spinbox": "微调框",
        "Spinner": "旋转器",
        "Switch": "开关",
        "Table": "表格",
        "Tabview": "标签页视图",
        "Textarea": "文本区域",
        "TileView": "平铺视图",
        "UserWidget": "用户组件",
        "SortArray": "排序数组",
        "Ascending": "升序",
        "Ignore case": "忽略大小写",
        "Structure name": "结构名称",
        "Structure field name": "结构字段名称",
        "For widget type": "组件类型",
        "New Font": "新建字体",
        "Font file": "字体文件",
        "Bits per pixel": "每像素位数",
        "Font size (pixels)": "字体大小 (像素)",
        "Ranges": "范围",
        "Ranges and/or characters to include. Example: 32-127,140,160-170,200,210-255": "要包含的范围和/或字符。示例：32-127,140,160-170,200,210-255",
        "Symbols": "符号",
        "List of characters to include. Example: abc01234äöüčćšđ": "要包含的字符列表。示例：abc01234äöüčćšđ",
        "Rendering engine": "渲染引擎",
        "Create characters": "创建字符",
        "Destination folder": "目标文件夹",
        "Store image and font files in a separate folder": "将图像和字体文件存储在单独的文件夹中",
        "Source code": "源代码",
        "Binary": "二进制",
        "LVGL include": "LVGL 头文件包含路径",
        "Screens lifetime support": "屏幕生命周期支持",
        "Generate source code for EEZ Flow engine (eez-framework)": "为 EEZ Flow 引擎生成源代码 (eez-framework)",
        "Compress flow definition": "压缩流程定义",
        "Execution queue size": "执行队列大小",
        "Expression evaluator stack size": "表达式评估栈大小",
        "Image export mode": "图片导出模式",
        "Font export mode": "字体导出模式",
        "ADV_HITTEST": "高级命中测试",
        "IGNORE_LAYOUT": "忽略布局",
        "FLOATING": "浮动",
        "OVERFLOW_VISIBLE": "溢出可见"
    }
};

function normalizeLocale(locale: string) {
    if (!locale) return "en";
    const lower = locale.toLowerCase();
    if (
        lower === "zh" ||
        lower.startsWith("zh-cn") ||
        lower.startsWith("zh_cn") ||
        lower.startsWith("zh-hans")
    )
        return "zh-CN";
    if (lower.startsWith("zh-tw")) return "zh-CN";
    if (lower.startsWith("en")) return "en";
    return locale;
}

export function t(key: string, fallback?: string) {
    const locale = normalizeLocale(getLocale());
    const table = translations[locale] || translations.en;
    const v = table[key];
    if (v != undefined) return v;
    if (fallback != undefined) return fallback;
    return key;
}
